services:
  - type: web
    name: acadex
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install --prefix whatsapp && npm install
    startCommand: node whatsapp/bot-acadex-secure.js
    envVars:
      - key: NODE_VERSION
        value: 20.20.2
      - key: ADMIN_PHONE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: TRIGGER_PHRASE
        value: mhoro acadex
